#!/bin/sh

DIRPATH="${SYNOPKG_PKGDEST}/application"
LINKPATH="/usr/syno/synoman/webman/3rdparty/synoAuth"
          
case $1 in                                             
        start)                                                   
                # Link application/desktop redirection
				ln -s "${DIRPATH}" "${LINKPATH}"
				exit 0
                ;;
        stop)
				# Unlink application/desktop redirection
				rm "${LINKPATH}"
                exit 0
                ;;                        
        status)                            
                if [ -e "${LINKPATH}" ]
				then
					echo "synoAuth is running..."
					exit 0
				else
					echo "synoAuth is shutdown..."
					exit 1
				fi
				exit 1
                ;;                 
        log)                                                             
                exit 0
                ;;                                  
        *)                   
                echo "Usage: $0 {start|stop|status|log}" >&2
                exit 1                     
                ;;
esac                                        
 


